# Use generic build mode on Ubuntu
image: Ubuntu
build: off

environment:
  CODECOV_TOKEN: 'b3e43b2a-8ab4-4dfc-a065-64850e7d982d'

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - nvm use 16
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
